export const CHANGE_TOP_LIST = 'ranking/CHANGE_TOP_LIST'
export const CHANGE_PLAY_LIST_ALL_SONGS = 'ranking/CHANGE_PLAY_LIST_ALL_SONGS'
export const CHANGE_COMMENT_INFO = 'ranking/CHANGE_COMMENT_INFO'